ubccr/xdmod-appkernels

- composer.json
- composer.lock
Update lock file with php-codesniffer dependency stuck to a specific version, bring all repositories in line with same version
Make sure all composer.lock files match composer 1.3.x version
ran composer install without errors.
> update composer and php-codesniffer dep

- .travis.yml
See ubccr/xdmod-supremm#34.
See ubccr/xdmod-supremm#34.
> Travis: Cache npm cache directory instead of node_modules directories

- classes/AppKernel/AppKernelDb.php
- classes/AppKernel/InstanceData.php
Fixed up xdmod core source based on the output of php7cc version compatibility checker (https://github.com/sstalle/php7cc). This provided an opportunity to delete some woefully dated source code that used deprecated syntax and packages.
Refer to pull requests against https://github.com/ubccr/xdmod/pull/101 and https://github.com/ubccr/xdmod-xsede/pull/29 repos for associated changes for php7 compatibility.
As spelled out in the original commit remarks:
- Renamed an AppKernel namespace class from Resource to AKResource
This PR helps prepare xdmod for a migration to a newer PHP version, and provides the opportunity to prune some unused and outdated code.
All existing integration and unit tests were run without incident. Where coverage is limited (e.g. user profile), manual testing was done …
> AppKernel: modify xdmod source for php7 compatibility

- configuration/assets.d/appkernels.json
The added JavaScript asset was incorrectly being included in the base
Open XDMoD package.
Adds a JavaScript asset to the internal dashboard.
See ubccr/xdmod#113
This JavaScript file was previously being incorrectly included in the base Open XDMoD package.
Installed with and without App Kernels module.  Confirmed that the tag was present only when the App Kernels module is installed and that no JavaScript errors were produced.
> Update asset configuration

- build.json
- xdmod-appkernels.spec.in
Added the modules.d/appkernels.json file to the file_maps section of
build.json
So that the new file would be included in the packaged module / installed when 'install' is executed. 
Manual test performed: 
- modified build.json w/ the new entry in file_maps/etc
- executed: \<xdmod_dir\>/open_xdmod/build_scripts/build_package --module appkernels --skip-assets --verbose
- cd \<xdmod_dir\>/open_xdmod/build
- tar xvzf xdmod-appkernels-6.7.0.tar.gz
- ls -alh configuration/modules.d/appkernels.json
- ensure that the file exists
- cat configuration/modules.d/appkernels.json
- ensure that it is a json file and that it contains the correct information
> Adding ETL related files for the appkernels module

- classes/Rest/Controllers/AkrrControllerProvider.php
- classes/Rest/Controllers/AppKernelControllerProvider.php
- configuration/rest.d/akrr.json
- configuration/rest.d/app_kernel.json
Just migrating the `NewRest` namespace to `Rest` as we've migrated everything from the old `Rest` namespace to `NewRest`.
Code cleanup
All unit, component, integration and regression tests were run / passed.
> Renaming NewRest -> Rest

- build.json
should remove the .eslintrc.json from the build so that the rpm can co-exist peacefully with xdmod.
> remove eslintjson.rc from rpm builds

- build.json
- configuration/linker.d/appkernels.json
This new file contains the AppKernels specific entry that was removed from
XDMoD's `linker.json` file.
So that this module will work w/ XDMoD's `linker.php` when installed.
> Adding a linker.d file for AppKernels

- html/internal_dashboard/js/Arr/AppKernelDashboardPanel.js
The layout of the tab body on the "App Kernels" tab on the internal dashboard is wrong on firefox linux.
> Fix App Kernels tab in internal dashboard

- classes/AppKernel/PerformanceMap.php
This print statement was causing the `App Kernels` -> `Reports` -> `Send X
Report` functionality to lock up XDMoD ( Due to HTML being returned which made
it no longer valid json )
Not locking up XDMoD == good
Manual Testing was performed
> Removing unneeded `print` statement

- classes/Rest/Controllers/AppKernelControllerProvider.php
This functionality was originally added for OpenXDMoD and as such did not take into
account that PO would also be utilizing this endpoint. Logic has been added to the
options building that defaults to not restricting the resources
returned, but if the user does not have  then they are restricted to seeing only
the resources they have access to.
To allow PO's to utilize this rest endpoint.
Manual testing on my dev port
> Updates to allow for PO usage

- classes/AppKernel/AppKernelIngestor.php
Fixed not setting ak_id for known appkernels during ingestion. This bug appears couple commits earlier on the fix of  setting ak_id for unknown appkernels (upon first ingestion)
> fixed not setting ak_id for known appkernels during ingestion

- CHANGELOG.md
- tests/runtests.sh
- xdmod-appkernels.spec.in
Update changelog for 10.5 release. COMPOSER=composer-el7.json was added so that composer would run since it was looking for composer.json, which does not exist.
> Update changelog for 10.5 release

- classes/AppKernel/Arr/Explorer.php
- classes/AppKernel/PerformanceMap.php
- classes/AppKernel/ProblemDetector/AppKernelLevel.php
- classes/AppKernel/RunsStats.php
Updates to address PHP8 incompatibilities. Mainly of the "Can only pass variables by-ref" type.  
We want to support PHP8 for XDMoD 11.0.
> Updates to support PHP8

- classes/AppKernel/ProblemDetector/AppKernelLevel.php
- classes/AppKernel/ProblemDetector/ResourceLevel.php
- Added a default value of `array()` for the `$problemsAppKernelLevel` argument of `AppKernelLevel::detect` and it's child class `ResourceLevel`. 
`AppKernelLevel::detect()`'s argument $problemsAppKernelLevel needs to have a default value provided.
Manual Checking performed.
> Adding default argument value for AppKernelLevel::detect

- html/.eslintrc.json
- html/gui/js/modules/app_kernels/AppKernelViewer.js
- html/internal_dashboard/js/Arr/ControlRegionsPanel.js
- html/internal_dashboard/js/Arr/SchedulePanel.js
Replaces any jQuery calls with native JavaScript. This PR is dependent on the[ base xdmod jQuery PR](https://github.com/ubccr/xdmod/pull/1756). Most of the changes are with the AppKernel Scheduler displayed in the internal dashboard.
**Note:** There is a bug with creating tasks in the internal dashboard `App Kernels` &#8594; `Schedule` tab. This is the exception thrown when trying to create a task: 
`Call to undefined method Rest\Controllers\AkrrControllerProvider::_parseRestArguments()`
jQuery is a large dependency that we use very sparingly.
Ran tests in docker container and viewed changes on xdmod-dev.
> Replacing jQuery with native JS

- html/gui/js/modules/app_kernels/AppKernelViewer.js
Issue found in XDMoD 11.0.0 bug testing
Before:
After:
Fix is visible on my developer port 9004
> Fix broken title and credits for App Kernel Viewer summary charts

- CHANGELOG.md
- xdmod-appkernels.spec.in
This PR updates the changelog to set the release date for v11.0.0 to the date the RPMs were actually built instead of the date we anticipated they would be built.
It also fixes a link formatting bug.
> Fix changelog.

- CHANGELOG.md
- build.json
- docs/_config.yml
This PR prepares the `xdmod11.0` branch for development of version `11.0.1`. It depends on https://github.com/ubccr/xdmod/pull/1939.
> Prep for v11.0.1 development.

- .circleci/config.yml
- CHANGELOG.md
- build.json
- docs/_config.yml
- xdmod-appkernels.spec.in
This PR prepares the `main` branch for development of version `11.5.0`. It depends on https://github.com/ubccr/xdmod/pull/1940.
> Prep for v11.5.0 development.

- CHANGELOG.md
- build.json
- xdmod-appkernels.spec.in
Port of https://github.com/ubccr/xdmod-appkernels/pull/124 for the `main` branch.
> Update changelog for 11.0.1.

- CHANGELOG.md
- build.json
- classes/AppKernel/AppKernelDb.php
- configuration/portal_settings.ini
- docs/_config.yml
- xdmod-appkernels.spec.in
This PR reverts changes for 10.5.1. There will be no 10.5.1 release for `xdmod-appkernels`.
> Revert changes for 10.5.1.
