ubccr/xdmod-appkernels

CHANGELOG.md, xdmod-appkernels.spec.in
Changes the 6.5.0 release date to 2017-01-10 in the change log and spec file.
We plan to release version 6.5.0 on this date, so that date should be used.
No tests performed.
=> Update 6.5.0 release date

CHANGELOG.md, xdmod-appkernels.spec.in
=> Merge #6 into 6.6

docs/_includes/menu.md
This pull requests adds links to the website for the application kernel repositories on GitHub.
This ensures every Open XDMoD website has a "Developing" section in its side menu.
=> Website: Added links to GitHub repos

.travis.install.sh, docs/_includes/menu.md
Merge pull request #9 into Open XDMoD Application Kernels Module 6.6.
=> Merge #9 into 6.6

.eslintrc.json, package.json
This pull request applies ubccr/xdmod#67 to this repository.
See ubccr/xdmod#67.
See ubccr/xdmod#67.
=> Updated ESLint and applied new XDMoD rules

build.json, configuration/assets.d/appkernels.json
=> Generate asset html tags

xdmod-appkernels.spec.in
=> Pre-release update

build.json, configuration/portal_settings.ini, xdmod-appkernels.spec.in
Updates version numbers to 6.6.0.
=> Update version numbers

CHANGELOG.md, xdmod-appkernels.spec.in
This pull request updates the change log for the release of version 6.6.0. The release notes are contained in ubccr/xdmod#96. The release notes contain user-friendly lists of changes, whereas the change log contains deeper, more technical notes.
**Please do not merge until dates and notes are finalized.**
Verified file rendered as expected.
=> Added change log for 6.6.0

CHANGELOG.md, configuration/assets.d/appkernels.json, xdmod-appkernels.spec.in
Merges xdmod6.6 into xdmod6.7
File conflicts:
- `build.json`
- `configuration/portal_settings.ini`
- `xdmod-appkernels.spec.in`
=> Merge xdmod6.6 into xdmod6.7 (#17, #19, #23)

.travis.yml, CHANGELOG.md, classes/AppKernel/AppKernelDb.php, classes/AppKernel/InstanceData.php, configuration/assets.d/appkernels.json, xdmod-appkernels.spec.in
Merges xdmod6.7 into xdmod7.0
File conflicts:
- build.json
- configuration/portal_settings.ini
- xdmod-appkernels.spec.in
=> Merge xdmod6.7 into xdmod7.0 (#17, #18, #19, #21, #22, #23, #24)

.travis.install.sh, package-lock.json
See ubccr/xdmod#150.
See ubccr/xdmod#150.
I verified that the main packages pulled in by this module match those pulled in by Open XDMoD, which was confirmed to work.
=> Added npm lock file

classes/AppKernel/Report.php
Update to the new mailwrapper so that sending reports works
=> Update mail wrapper

html/gui/js/modules/AppKernels.js, html/gui/js/modules/app_kernels/AppKernelViewer.js
Viewer.tokenize no longer exists. Also remove dead code that was
referencing Viewer.tokenize.
viewer.tokenize no longer exists.
none
-  Bug fix (non-breaking change which fixes an issue)
=> Replace calls to Viewer.tokenize with CCR.tokenize

classes/AppKernel/Report.php
I made some mail changes that correspond to the changes made in XDMoD so that everything works together.
Changes in XDMoD require that these changes be made so nothing fails when using appkernels.
Tests have been previously run on XDMoD and have succeeded.
=> Mail fixes

CHANGELOG.md, xdmod-appkernels.spec.in
This pull request updates the change log for the release of version 7.0.0. The release notes are contained in ubccr/xdmod#226. The release notes contain user-friendly lists of changes, whereas the change log contains deeper, more technical notes.
**Please do not merge until dates and notes are finalized.**
Verified file rendered as expected.
=> Updated release notes and change log for 7.0.0

.travis.build.sh, .travis.install.sh, .travis.yml
Removes 5.3.3 from travis builds.
See ubccr/xdmod-supremm#66
=> Update travis per other repos

xdmod-appkernels.spec.in
Changes RPM dependency to strictly require Open XDMoD 7.0.x to prevent problems with upgrading `xdmod` and not `xdmod-appkernels`.
See ubccr/xdmod-supremm#67
Trying to reduce upgrade issues in the future.
No new tests.
=> Update xdmod RPM dependency

CHANGELOG.md, xdmod-appkernels.spec.in
This updates the change log/release notes to include some final pull requests for 7.0.0.
I oops'd and merged the previous pull request for this purpose before we were actually done. Sorry about that and the resulting email spam, all.
- Documentation update
=> Updated 7.0.0 change log

.travis.build.sh, .travis.install.sh, .travis.yml, CHANGELOG.md, build.json, xdmod-appkernels.spec.in
This pull request merges work done for 7.0 into the 7.1 branch. Merged pull requests include: #28, #34, #35, #36, and #37.
=> Merge 7.0 work into 7.1

xdmod-appkernels.spec.in
=> Update RPM spec file

classes/DataWarehouse/Access/DataExplorer.php, classes/DataWarehouse/Visualization/HighChartAppKernel.php, classes/NewRest/Controllers/AppKernelControllerProvider.php, html/gui/js/modules/app_kernels/AppKernelViewer.js
=> Add pdf support.

CHANGELOG.md, configuration/cron.conf, configuration/portal_settings.ini, xdmod-appkernels.spec.in
=> Release preparations

CHANGELOG.md, build.json, configuration/portal_settings.ini, xdmod-appkernels.spec.in
=> version upgrade

classes/DataWarehouse/Visualization/HighChartAppKernel.php, classes/NewRest/Controllers/AppKernelControllerProvider.php, html/gui/js/modules/app_kernels/AppKernelViewer.js, html/internal_dashboard/js/Arr/ControlRegionsPanel.js
These changes depend on:
https://github.com/ubccr/xdmod/pull/533
=> Remove javascript from charts

classes/DataWarehouse/Access/DataExplorer.php, classes/DataWarehouse/Visualization/HighChartAppKernel.php, classes/Rest/Controllers/AppKernelControllerProvider.php
Added an XDUser parameter to instantiations of the HighChartAppKernel class.
The HighChartAppKernel class needed to have an XDUser parameter added / piped to the parent constructor.
All instantiations of this class needed to have this new parameter added.
This PR should be merged at the same time as: https://github.com/ubccr/xdmod/pull/572
=> Updating HighChartAppKernel Constructor & Call Sites

CHANGELOG.md, xdmod-appkernels.spec.in
Updating documentation for the upcoming XDMoD 8.0 release
=> Updating changelog for xdmod8.0 release

xdmod-appkernels.spec.in
update the spec file to be limited to `< 8.1`
=> update spec file to be more restrictive

CHANGELOG.md, build.json, configuration/portal_settings.ini, xdmod-appkernels.spec.in
=> Updates for release 8.1

xdmod-appkernels.spec.in
This should have been part of #57
=> Add linker file to spec file

build.json, configuration/portal_settings.ini, xdmod-appkernels.spec.in
=> Update version numbers to 8.5

build.json, configuration/roles.d/appkernels:summary.json, html/gui/js/modules/summary/CenterReportCardPortlet.js
- Use the standard portlet aspect ratio
- Use standard naming convention for .d files
- Update the tooltip text
=> Minor UI changes to Center Report Portlet

CHANGELOG.md, xdmod-appkernels.spec.in
=> update release notes and changelogs

CHANGELOG.md, xdmod-appkernels.spec.in
=> Update release date

Dockerfile, classes/AppKernel/AppKernelDb.php, classes/AppKernel/AppKernelIngestor.php, classes/AppKernel/InstanceData.php, classes/Rest/Controllers/AppKernelControllerProvider.php, tests/README.md, tests/artifacts/mod_appkernel_xdmod_dev_test.sql, tests/runtests.sh
* added developer and manager to be able to have center report card for all centers
* added testing that xdmod_resource_id refer to actual resource from modw
* removed yum update from Dockerfile for shippable
=> removed update from Dockerfile for shippable

classes/AppKernel/PerfPatternRecognition.php
Fixed access to mod_appkernel using modw connector. It failes when db are on different hosts.
=> Fixed access to mod_appkernel using modw connector

build.json, xdmod-appkernels.spec.in
=> Update spec file

Dockerfile, build.json, configuration/portal_settings.ini, docs/_config.yml, shippable.yml, tests/README.md, xdmod-appkernels.spec.in
=> initial 9.5

bin/xdmod-akrr-ingestor
replace require_once linker.php from /usr/share/xdmod/configuration/linker.php to __DIR__ . '/../configuration/linker.php'
=> replace require_once linker.php from /usr/share/xdmod/configuration/linker.php to __DIR__ . '/../configuration/linker.php'

bin/xdmod-akrr-ingestor, classes/AppKernel.php, classes/AppKernel/AppKernelDb.php, classes/AppKernel/AppKernelIngestor.php, classes/AppKernel/Arr/Explorer.php, classes/AppKernel/Arr/Parser.php, classes/AppKernel/iAppKernelExplorer.php, classes/AppKernel/iAppKernelParser.php, shippable.yml, tests/runtests.sh
~~**Note: https://github.com/ubccr/xdmod/pull/1461 needs to be merged before this PR.**~~ This PR has been merged so we're good to go.
~~**After the above PR is merged then XDMOD_BRANCH & XDMOD_ORG_NAME will need to be updated to `xdmod9.5` and `ubccr` respectively.**~~ Same as above
These changes migrate away from using the PEAR Log class to using the standardized PSR\Log specification w/ Monolog providing the implementation. 
PEAR Log is no longer being supported so by migrating to using the PSR\Log standard we can help future proof our logging infrastructure.
=> Pear Log -> Monolog migration

.circleci/config.yml, tests/runtests.sh
=> Adding required config files for CircleCI integration

CHANGELOG.md, xdmod-appkernels.spec.in
Update change log and SPEC file.
Preparing for 9.5.0 release.
No tests.
=> Update change log for 9.5.0

.circleci/config.yml, CHANGELOG.md, Dockerfile, build.json, configuration/portal_settings.ini, docs/_config.yml, shippable.yml, tests/README.md, xdmod-appkernels.spec.in
Update all the version numbers, etc.
Preparing for 10.0 development.
No new tests.
=> 10.0 release branch

bin/appkernel_reports_manager, bin/xdmod-akrr-ingestor
Set the log level to `NOTICE` when no verbose, debug, quiet or dry-run option is set.
The value `-1` for the log level is causing exceptions:
```
-------------------------------------------------------
2021-09-04 01:00:01 [error] Exception Code: 0
2021-09-04 01:00:01 [error] Message: Unknown Log Level
2021-09-04 01:00:01 [error] Origin: /data/www/xdmod/share/classes/CCR/Log.php (line 395)
2021-09-04 01:00:01 [error] Trace:
#0 /data/www/xdmod/share/classes/CCR/Log.php(223): CCR\Log::convertToMonologLevel(-1)
#1 [internal function]: CCR\Log::getConsoleHandler('xdmod-akrr', Array)
#2 /data/www/xdmod/share/classes/CCR/Log.php(192): call_user_func(Array, 'xdmod-akrr', Array)
#3 /data/www/xdmod/share/classes/CCR/Log.php(113): CCR\Log::getLogger('xdmod-akrr', Array)
#4 …
```
=> Set default log level for command line utilities

CHANGELOG.md, xdmod-appkernels.spec.in
Update change log.
Preparing for release.
=> Update change log

.circleci/config.yml, CHANGELOG.md, Dockerfile, build.json, configuration/portal_settings.ini, docs/_config.yml, shippable.yml, tests/README.md, xdmod-appkernels.spec.in
- Change version numbers.
- Change Docker images.
New release branch.
=> 10.5 boilerplate

_config.yml
Same as https://github.com/ubccr/xdmod/pull/1811 for `xdmod-appkernels` website.
This PR also fixes the missing version number in the banner on the unsupported version pages.
=> Update list of supported versions on website.

.gitignore, classes/DataWarehouse/Access/DataExplorer.php, classes/DataWarehouse/Visualization/AppKernelChart.php, classes/DataWarehouse/Visualization/HighChartAppKernel.php, classes/Rest/Controllers/AppKernelControllerProvider.php, html/.eslintrc.json, html/gui/js/modules/app_kernels/AppKernelExplorer.js, html/gui/js/modules/app_kernels/AppKernelViewer.js, html/internal_dashboard/js/Arr/AppKerSuccessRatePlotPanel.js, html/internal_dashboard/js/Arr/ControlRegionsPanel.js
These changes are for the appkernels explorer, viewer, and internal dashboard.
When finding a bug please compare with an instance running Highcharts so we know if this is an existing bug or not.
Features not in Plotly JS yet
- Hover events styling marker and line sizes
- Shadow
Plotly JS has no license requirement which is desirable for Open XDMoD.
Tested on docker and dev-port. Will be converting the Playwright tests to work with Plotly JS.
=> Conversion of Highcharts to Plotly JS

classes/AppKernel/Arr/IncaParser_Performance.php, composer.json, composer.lock
Updating XDMoD Appkernels to use PHP 7.4.
=> Xdmod11.0 PHP 7.4

.circleci/config.yml, classes/AppKernel/AppKernelIngestor.php
This should have been in the last PR but was missed. 
- Note, also updated the `test` logic to match XDMoD's.
=> Updating CircleCI to use PHP 7.4

.gitignore, html/.eslintrc.json
Remove `jQuery` from `.gitignore` file. jQuery was removed in PR #108 
Consistent `.gitignore`
=> Partial jQuery Rollback

build.json
=> Bumping for 11.0 rc.1

build.json
=> bumping to rc.2

CHANGELOG.md
This PR updates the changelog with the changes for 11.0.
TODO: Update release date.
=> Update changelog for 11.0.

CHANGELOG.md, build.json, xdmod-appkernels.spec.in
Update `xdmod-appkernels.spec.in` and `build.json` files for xdmod-appkernels 11.0.0 release
=> Update `spec.in` and `build.json` files for 11.0 release

docs/_data/toc.yml
This PR adds a link to the upgrade guide in the table of contents.
=> Add upgrade guide to table of contents.

.circleci/config.yml, CHANGELOG.md, build.json, xdmod-appkernels.spec.in
Same as https://github.com/ubccr/xdmod/pull/1950 for the `xdmod-appkernels` module.
=> Update changelog for 11.0.1.

.circleci/config.yml, CHANGELOG.md, build.json, classes/AppKernel/AppKernelDb.php, configuration/portal_settings.ini, docs/_config.yml, tests/runtests.sh, xdmod-appkernels.spec.in
This PR also fixes a PHP error when calculating control regions, which was exposed by the CI tests.
=> Prepare for v10.5.1 release.
